

loader_params: 

    'train_bs': 1
    'val_bs': 1
    'csv_root': 'meta_files/meta_data_infer_val.csv'
    'scale_dose_dict': 'meta_files/PTV_DICT.json'
    'pat_obj_dict': 'meta_files/Pat_Obj_DICT.json'
    'num_workers': 2

    'down_HU': -1000
    'up_HU': 1000
    'denom_norm_HU': 500

    'in_size': [176, 160, 272]
    'out_size': [176, 160, 272]
    'norm_oar': True
    'CatStructures': False
    'dose_div_factor': 10 
    
    
model_params:
    num_input_channels: 8
    out_channels: 1
#    model_id: 'B'
    model_id: 'L'
    kernel_size: 3
    deep_supervision: False


act_sig: True
scale_out: 12.0
scale_loss: 4

model_from_lightning: False
save_model_path: checkpoint/train.pth
save_pred_path: /results


